# Generated by Django 3.2.23 on 2024-04-04 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_privateconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='private_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.privateconversation'),
        ),
    ]
