# Generated by Django 5.0.4 on 2024-04-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Lower', 'Lower Level'), ('Lower', 'Lower Level')], max_length=25, null=True),
        ),
    ]
