# Generated by Django 5.0.4 on 2024-04-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
